version: '3.4'

services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      GAMEMODE: survival
      DIFFICULTY: normal
      OPS: "2533274837393509"
      SERVER_NAME: "Gage Street"
    ports:
      - 19132:19132/udp
    volumes:
      - ./services/minecraft/data:/data
    stdin_open: true
    tty: true
    
